### PR TITLE
Solarized color fix

### LINKED ISSUE #84: Some airbrussh output is "invisible" in certain terminal color schemes
We've received multiple reports (from @Startouf and @dan-klasson in https://github.com/capistrano/capistrano/issues/1669) that important error messages are not being rendered by Airbrussh.

Specifically, the color of the message is indistinguishable from the background color of the terminal, making them "invisible".

Suggestions of how to reproduce this (what OS and terminal is affected?) and how to fix it would be greatly appreciated.

234c8794-1612-11e6-9f86-00bf3e6686e3

### PR DESCRIPTION
**Pull request by huerlisi**
Fixes #84 Some airbrussh output is "invisible" in certain terminal color schemes

### CODE REVIEW

**Comment by mattbrictson** [comment]
Looks like RuboCop has dropped support for Ruby 1.9, which is causing Travis to fail. Can you update `airbrussh.gemspec` to pin Rubocop at 0.41, like this? Thanks.

```ruby
spec.add_development_dependency "rubocop", "~> 0.41.2"
```

**Comment by mattbrictson** [comment]
Also, please add a bullet under the `Unreleased` section of `CHANGELOG.md` describing the change and referencing #89. Otherwise this is looking great! Thanks 🙇

**Comment by huerlisi** [comment]
All green:-)

**Comment by mattbrictson** [comment]
Excellent work. Thanks! 👍

**Comment by huerlisi** [comment]
Was a pleasure, very good hints from your side!

**Pull request merged**
