### PR TITLE
Update tests to work with sshkit master / unknown user

### PR DESCRIPTION
**Pull request by felixbuenemann**
This accounts for changes in sshkit's local username lookup introduced by capistrano/sshkit#293 and also accounts for the conditional formatting changes introduced by #66.

The latter did not previously cause failed tests, because the username was stubbed in the tests, causing the relevant code to not be exercised.

Now the username is looked up through sshkit, which results in an empty username on sshkit < 1.7.0, so the no-username display is triggered ("on host" vs. "as foo@host").

### CODE REVIEW

**Comment by mattbrictson** [comment]
Great! I like that this also simplifies the test setup somewhat. I'll merge once CI is complete.

**Comment by felixbuenemann** [comment]
Yes, I'm not fan of stubs if they can be avoided.

Maybe there should be an explicit tests for the "user@host" vs "host" formatting?

**Comment by felixbuenemann** [comment]
The appveyor tests now run into sshkit's windows incompatibility before the changes to master, so maybe we need to keep the Etc stub for that?

**Comment by mattbrictson** [comment]
Yes, you're right. Unfortunately I think the `Etc` stub needs to stay in there, for Windows SSHKit <= 1.7.1.

**Comment by felixbuenemann** [comment]
OK, I've added back the Etc stub for sshkit <= 1.7.1.

**Comment by mattbrictson** [comment]
Thanks!

**Pull request merged**
