### PR TITLE
Don't attempt to truncate output to 0 width

### PR DESCRIPTION
**Pull request by byroot**
Ref: https://github.com/Shopify/shipit-engine/issues/529

When ruby is executed via [`PTY.spawn`](http://ruby-doc.org/stdlib-2.1.0/libdoc/pty/rdoc/PTY.html) `IO.console.winsize` returns `[0, 0]`.

And when that happens Airbrush get stuck in an infinite loop.

@mattbrictson / @leehambley.

cc @teu @PatKoperwas

### CODE REVIEW

**Comment by leehambley** [comment]
Just out of curiosity do you have a sample `PTY.spawn` wrapper you can share I can use to reproduce this?

**Comment by PatKoperwas** [comment]
from https://github.com/mattbrictson/airbrussh/issues/75

```ruby
require "pty"

PTY.spawn("cap staging deploy" ) do |stdout, stdin, pid|
  begin
    stdout.each { |line| print line }
  rescue Errno::EIO
  end
end
```

**Comment by mattbrictson** [comment]
Thanks for the fix and for the test! Can you add a CHANGELOG entry under the "Unreleased" heading?

I'll try to get a 1.0.1 release out the door next week with this included.

**Comment by byroot** [comment]
Changelog updated!

**Comment by mattbrictson** [comment]
Thanks! :raised_hands:

**Comment by mattbrictson** [comment]
1.0.1 released: https://rubygems.org/gems/airbrussh/versions/1.0.1

**Pull request merged**
