### PR TITLE
Explicit command logging methods

### PR DESCRIPTION
**Pull request by robd**
This PR includes the necessary refactoring to support the new https://github.com/capistrano/sshkit/pull/257

It is based on #15, so that should probably be merged first if you are happy with the changes there.

The tests now run and pass against both master and [the SSHKit PR 257 branch](https://github.com/robd/sshkit/tree/deprecate-command-stdstream-state). This means the I kept support for the intermediary [`clear_stdout_lines`](https://github.com/mattbrictson/airbrussh/compare/master...robd:explicit-command-logging-methods?expand=1#diff-faf9277ec199ea9f2e313151176a085eR161) method, but I would suggest we remove support for that because, assuming PR257 is merged, the SSHKit version including `clear_stdout_lines` will never have been released. If you are happy with that, then I will remove support for `clear_stdout_lines`, perhaps once PR257 is merged in SSHKit.

I ended up having to do quite a bit of refactoring work in order to support both the new `log_command_start`, `log_command_data`, `log_command_exit` entry points and the old `write` one. If we were to merge this into SSHKit, much of the code could be simplified, and certainly the tests could be.

### CODE REVIEW

**Comment by robd** [comment]
capistrano/sshkit#257 has now been merged so I need to rework things a bit. If you don't mind, please do not merge this until I have sorted things out a bit.

**Comment by robd** [comment]
OK, this has turned into a complete nightmare. None of the commits apply cleanly without ebdad32. 

I'm going to have to basically start this work again because I shouldn't have based it on #15, which it now turns out didn't work. I don't know how you feel about #15, but I'm going to try and leave the monkey patching code untested and just fix things now that https://github.com/capistrano/sshkit/pull/257 has been merged.

**Comment by mattbrictson** [comment]
@robd I am pretty busy this week, so it may take me a while to review and respond to these PRs. Thanks for all your work so far!

**Comment by robd** [comment]
Hi @mattbrictson 

OK no problem. I have reimplemented this PR with a cut down set of changes so this will be less to review. This PR fixes the critical problem of Airbrussh being broken against master SSHKit since https://github.com/capistrano/sshkit/pull/257 was merged.

I left out 2 things from the PR:

1) [Improvements to rake task integration testing](https://github.com/robd/airbrussh/commit/ebdad32eba85162b3c2234449ab70484534ed169) (currently tests do not test rake monkey patch).
2) [Inline of the `CommandOutput` strategy class](https://github.com/robd/airbrussh/commit/4054530b1ac64a8a4da93ba28e6bd74860f7651b)

I would be happy to revisit these once Airbrussh works against SSHKit master again.

Currently I test against these versions of SSHKit:
* master (including https://github.com/capistrano/sshkit/pull/257)
* previous unreleased master pre PR257 ( https://github.com/capistrano/sshkit/commit/ea211bcbbb71dab0152a18c2774922b7017e4edc)
* 1.7.1
* 1.6.1

I would recommend dropping support for https://github.com/capistrano/sshkit/commit/ea211bcbbb71dab0152a18c2774922b7017e4edc, (this is the version with the `clear_#{stream}_lines` methods).  This would allow the `Modern` `CommandOutput` to be deleted, and the legacy behaviour could then be inlined.

Also, the `Formatter` class is now too long so I disabled the rubocop check in b9f59b6. I think one candidate for a separate class is the command history code relating to the `@tasks` attribute. Again, I would be happy to work on a PR for this once Airbrussh works on master again, but I don't want to fall in to the trap of getting too far ahead.

Anyway, I hope this makes sense - happy to talk more when you have a chance to review.

**Comment by mattbrictson** [comment]
@robd This PR is already a bit too big for me to fully review right now. I think we will need some more time to fully hash out the best way to refactor everything. Also, it looks like `log_command_data` is not honoring `Airbrussh.configuration.command_output`, so there may need to be some further tweaks.

In the meantime do you think we can move forward with #18 for now?

**Comment by robd** [comment]
Hey Matt

I guess I misunderstood completely that you just wanted to get something quick done here! I think this was just a communication mix up, but next time, I will query the parameters of what you want to me do (eg "I'd like a quick 1 commit patch which doesn't rework any code."). Getting a steer on this would have been really helpful because I now feel like perhaps I wasted a lot of time here!

Can you let me know where you stand with this PR. I can't tell if the work I did here was helpful and it's just that you want to get something quick done now, or if really you would prefer to do any refactoring required, and refactoring PRs aren't really something you want.

I think it would be good to add an automated test for the`Airbrussh.configuration.command_output` option. It would also be really helpful if you could share your manual test suite or steps if you prefer to use these over an automated ones. It think the fix for this is trivial; just missed because there are no tests.

I will look at the other PR now.

**Comment by mattbrictson** [comment]
@robd Sorry for the limited communication on my part. My assumption was that changes needed to support SSHKit master would be small, and if not, we would have some discussion on how to move forward.

This is my first open source project that has gotten significant attention (and contributions), so I am still learning how I should deal with things like refactoring PRs. Right now I feel that I am not ready to accept large PRs.

I'll keep this one open so that I can circle back to it once I have more time to work on airbrussh.

**Comment by robd** [comment]
@mattbrictson Thanks for sharing your thoughts on this. I'm sorry I didn't wait to discuss with you at the time. One difficulty was I happened to be working on this while you were quite busy so I didn't want to take up any of your time. The other problem was that it was very hard to know how big the PR would be until I got into the code - there were some assumptions in the code that no longer held true which I think needed some rework. I ended up just carrying on until those things were sorted out, but in retrospect I should have discussed these decisions as I went along.

I am new to open source contributions as well so I guess it takes a little time to find a way of working which suits everyone. I have always tried to refactor and add tests as I go along to try to avoid letting the debt pile up. But I forget sometimes that this is a personal preference and maybe not applicable when people don't have time to work on projects.

As far as improving this PR - is there anything I could do? 

I would be very happy to describe the problems I faced with integrating the new lifecycle methods and the rationale behind the commits and/or the refactoring as a whole.

When you say large PRs - could you explain a bit more here - does each commit look about the right size? Each commit is a self contained refactoring or behaviour change so I could split up the PR into a series of smaller ones if that would help.

**Comment by robd** [comment]
Just to follow up here, I rebased this on master, added a test for disabled command output and added a commit to remove the `CommandWithData`, so hopefully when you have more time to look, it will be a bit easier.

**Comment by mattbrictson** [comment]
@robd Thanks for the PR; I finally had a chance to review it! I like how you've refactored some of the formatter code into smaller methods like `debug?`, `shell_string`, and `first_execution?`. The test you've added for the disabled command output is also much appreciated.

I'm going to merge this in. Then with some free time I have this week, I am going to attempt some further refactoring and cleanup of my own. I'll open a PR so you can review, if you are curious.

**Comment by robd** [comment]
@mattbrictson Hey! Glad this was helpful in the end. I would be very happy to look at the other PRs - though I am a bit busy with client work just at the moment, so it may take me a few days.

:+1: Using DI for configuration object. Also saw updated contribution docs, release notes and added code coverage all very good stuff. Chandler looks like a really great idea. I have often thought how annoying it is trying to go backwards and forwards between github releases and changelog.

**Pull request merged**
